server:
  port: 8081

spring:
  application:
    name: transacional
  data:
    redis:
      host: redis
      port: 6379

  kafka:
    bootstrap-servers: ${KAFKA_URL:kafka1:19091}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

intermitente:
  base-url: ${INTERMITENTE_URL:http://localhost:8080/pagamentos/pagar}
