server:
  port: 8080
spring:
  application:
    name: intermitente

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
